### ISSUE TITLE
Batch prediction, GPU inference

### ISSUE THREAD

**Issue by Selimonder** [ocampor/image-quality#19]
Hello, first of all, thanks a lot for this great repo. I've been assessing the quality scores for series of videos, however, **.score** function feels like slowing things down. I've noticed all inference is going around CPU,

So,

1. Is there a quick way around for GPU inference?
2. Do you maybe have batched scoring logic implemented?

I think your pre-trained models would do the job but it might be a requested feature from other users as well.

Good luck

**Comment by ocampor** [comment]
The pipeline was written entirely for CPU. It is not part of the roadmap to migrate it to GPU; however, you are more than welcome to create a PR for it.

A quick solution for this is to move the matrix multiplications to a framework that supports GPU like google jax https://github.com/google/jax.

There would be a still some bottlenecks because of GPU/CPU data transferring, but I don’t have enough information to assess the magnitude.
