### ISSUE TITLE
Trying to Validate BRISQUE Output

### ISSUE THREAD

**Issue by blue-j** [ocampor/image-quality#31]
**Describe the bug**
I can't say I am sure there is a bug.  Installation is easy, and working fine, but the BRISQUE scores being output are not matching the ones from here:     [https://www.learnopencv.com/image-quality-assessment-brisque/]

which is typically a very reliable source, written by the CEO of OpenCV.

He reports these BRISQUE scores for these images:

original-rotated-image.jpg     26.8286
JPEG2k-compressed.jpg     30.7417
compressed-heavy.jpg     33.0692
noise-version.jpg     79.8751
blur-vision.jpg     72.7044

while your library reports quite different numbers for me:

original-rotated-image.jpg     54.6798
JPEG2k-compressed.jpg     53.9756
compressed-heavy.jpg     55.0188
noise-version.jpg     70.2104
blur-vision.jpg     63.5786

Perhaps I am misunderstanding something, and your codes are not trying to produce the same output?  I am a total amateur in the field of IQA.  And perhaps it is his code that is in error.  His metrics make more sense to me, looking at the imagery.

![blur-vision](https://user-images.githubusercontent.com/3990142/101294875-10876a00-37cf-11eb-97d2-f6b4cca4d092.jpg)
![noise-version](https://user-images.githubusercontent.com/3990142/101294876-11200080-37cf-11eb-8820-cb5b227f35e3.jpg)
![compressed-heavy](https://user-images.githubusercontent.com/3990142/101294877-11b89700-37cf-11eb-89ec-cd2577653eca.jpg)
![JPEG2k-compressed](https://user-images.githubusercontent.com/3990142/101294878-12512d80-37cf-11eb-8de0-d6c00384f085.jpg)
![original-rotated-image](https://user-images.githubusercontent.com/3990142/101294879-12512d80-37cf-11eb-9b73-7c8ebb2b8a65.jpg)

**Comment by blue-j** [comment]
Well, the plot thickens.  Output from his script doesn't match the output reported in the blog.  I will bring this to his attention.  Your numbers are close enough to chalk up to slight variable differences at this point.  I suppose this is good news!  : )

HIS:
blur-vision.jpg     63.9073
compressed-heavy.jpg     54.9763
JPEG2k-compressed.jpg     55.0107
noise-version.jpg     70.0947
original-rotated-image.jpg     54.2116

YOURS:
blur-vision.jpg 63.5786
compressed-heavy.jpg 55.0188
JPEG2k-compressed.jpg 53.9756
noise-version.jpg 70.2104
original-rotated-image.jpg 54.6798

**Comment by ocampor** [comment]
@blue-j Thanks for your thorough response. The code does not come from OpenCV. The authors of the BRISQUE paper published the code in C++ and Matlab. My job was to port the algorithm to python and make it easy to install. 

If you want to replicate 100% the results from the paper, I recommend you to take a look to the scaling step of the algorithm. The problem is that the original code uses the resize function of Matlab which is quite difficult to replicate in python.

I hope this information helps.

**Comment by krshrimali** [comment]
Hi, @ocampor - great work on the library.

I know that this is too late and also since I'm the author of the mentioned blog, I just wanted to mention this: in case someone wants to compare results, I suggest to refer to OpenCV's quality module. The algorithms (BRISQUE and a few more) were ported to `opencv_contrib`. 

Please see: https://github.com/opencv/opencv_contrib/tree/master/modules/quality. There were a few modifications made including the model used, and even though the blog is highly reliable, but still I would say to do the comparisons using the `quality` module in OpenCV. Thanks! :)
